app = "genzz-library-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "5000"
  NODE_ENV = "production"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[mounts]]
  source = "genzz_data"
  destination = "/data"
